# Generated by Django 3.2 on 2022-07-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0002_auto_20220704_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='cell',
            field=models.CharField(default='', max_length=13, verbose_name='Celular'),
        ),
    ]
