# Generated by Django 3.2 on 2022-08-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('subject', models.CharField(max_length=100, verbose_name='Assunto')),
                ('message_content', models.TextField(verbose_name='Menssagem')),
            ],
        ),
    ]
