# Generated by Django 3.2 on 2022-09-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='valor da cota')),
                ('url_image', models.CharField(max_length=300)),
            ],
        ),
    ]
