# Generated by Django 3.2 on 2022-10-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockExchange', '0002_auto_20220909_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rentabilidade'),
        ),
    ]
